[package]
name = "things-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
things-db = { path = "../things-db" }
rocket = "0.5.0"